### ISSUE TITLE
File Transfer with Android Device

### ISSUE THREAD

**Issue by alukowitz** [Duke-fleed/WPDApi#2]
I am trying to read and write files to an Android Device.  I was hoping to use this api.  Is there any example code on reading and writing files, seeing if a file exists, looking at directories beneath the root?  Any he,p would be greatly appreciated.

al

**Comment by Duke-fleed** [comment]
Hi!
Yes there is example code, it's inside ConsoleClient project, in Program.cs. I just updated it and added some helpful comments. You can check it out and see if everything is clear.

**Comment by alukowitz** [comment]
Thank you very much, I will give this a look today.

al

**Comment by alukowitz** [comment]
Thank you very much, I have been able to read and write files to my device.

al

**Comment by Duke-fleed** [comment]
You are very welcome. Good to hear :)

**Comment by alukowitz** [comment]
I have another questions, is it possible to update an Android app on the Android device using AndroidLib?  If  so, is there any example code or  documentation?

thank you in advance

al

**Comment by Duke-fleed** [comment]
Hello,

Have never used it myself, this code is helpful with file transferring only. Although will take a look and keep you updated if anything useful comes up :)

**Comment by alukowitz** [comment]
Thanks, any help would be greatly appreciated.

al
